const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=new URLSearchParams(location.search).get('id');const main=PORTFOLIO.featured.find(x=>x.id===id),minor=PORTFOLIO.archive.find(x=>x.id===id),project=main||minor,root=document.querySelector('#case-root');
const all=caseGallery(id);
const groupName={'ведати 1':'01 / ИССЛЕДОВАНИЕ','ведати 2':'02 / ПОИСК ФОРМЫ','ведати 3':'03 / РАЗВИТИЕ','ведати 4':'04 / САЙТ И СИСТЕМА'};
function mediaButton(path,label,extra=''){return `<button class="media-button ${extra}" type="button" data-src="${esc(path)}" aria-label="Открыть изображение: ${esc(label)}"><img src="${esc(path)}" alt="${esc(label)}" loading="lazy"><span>УВЕЛИЧИТЬ ↗</span></button>`}
if(!project){root.innerHTML='<div class="not-found"><h1>Проект не найден</h1><a href="index.html#projects">← К проектам</a></div>'}
else{
 document.title=project.title+' — Полина Березина';document.body.dataset.project=id;document.documentElement.style.setProperty('--project-color','#f1f1ee');
 const links=(project.links||[]).map(([text,url])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(text)} <b>↗</b></a>`).join('');
 const facts=(project.facts||[]).map(([a,b])=>`<div><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('');
 const menu=`<aside class="case-sidebar"><a class="sidebar-back" href="index.html#${main?'projects':'more'}">← К ПРОЕКТАМ</a><div class="sidebar-head"><span class="sidebar-num">${main?'0'+(PORTFOLIO.featured.indexOf(project)+1):'АРХИВ'} / ${esc(project.type)}</span><h1>${esc(project.title)}</h1><p>${esc(project.subtitle||project.desc)}</p><div class="sidebar-tags"><span>${esc(project.year||'Учебный проект')}</span><span>${esc(project.team||'Учебный проект')}</span></div></div><div class="sidebar-links">${links||'<span class="no-link">Визуальные материалы проекта</span>'}</div><div class="sidebar-disclosures"><details open><summary>О проекте <b>+</b></summary><p>${esc(project.intro||project.desc)}</p></details>${main?`<details><summary>Задача и процесс <b>+</b></summary><p>${esc(project.sections.slice(0,2).map(s=>s.text).join(' '))}</p></details><details><summary>Результат <b>+</b></summary><p>${esc(project.sections.slice(-2).map(s=>s.text).join(' '))}</p></details>`:''}</div><div class="sidebar-foot"><a href="#all-materials">ВСЕ МАТЕРИАЛЫ (${all.length}) ↓</a><span>ПОЛИНА БЕРЕЗИНА · 2026</span></div></aside>`;
 const visual=CASE_COVERS[id]||all[0]?.src||project.cover;
 const opening=`<div class="case-visual-header"><span>${esc(project.type)}</span><span>${esc(project.year||'АРХИВ')}</span></div><div class="case-hero-image">${mediaButton(visual,project.title+' — обложка проекта','cover-media')}<div class="case-hero-type"><span>ПРОЕКТ / ${main?'0'+(PORTFOLIO.featured.indexOf(project)+1):'АРХИВ'}</span></div></div><div class="case-lede"><span>ИДЕЯ</span><p>${esc(project.intro||project.desc)}</p></div>`;
 let story='';if(main){story=project.sections.map((section,i)=>{const images=CASE_STORY[id]?.[i]||[section.image];return `<section class="case-chapter" id="chapter-${i+1}"><div class="chapter-heading"><span>${esc(section.label)}</span><h2>${esc(section.title)}</h2><p>${esc(section.text)}</p>${section.link?`<a href="${esc(section.link[1])}" target="_blank" rel="noopener noreferrer">${esc(section.link[0])} ↗</a>`:''}</div><div class="chapter-images">${images.map((path,j)=>mediaButton(path,`${project.title} — ${section.title}, материал ${j+1}`,j===0?'primary-media':'secondary-media')).join('')}</div><div class="image-note"><span>${esc(section.caption)}</span><span>${String(i+1).padStart(2,'0')} / ${String(project.sections.length).padStart(2,'0')}</span></div></section>`}).join('')}
 const grouped=[];let current='';for(let i=0;i<all.length;i++){const item=all[i],group=item.module||item.group;if(group!==current){current=group;grouped.push(`<div class="gallery-group-title">${esc(groupName[group]||group||'МАТЕРИАЛЫ ПРОЕКТА')}</div>`)}const thumb=item.thumb||item.src.replace('/full/','/thumbs/');grouped.push(`<button class="gallery-thumb" type="button" data-src="${esc(item.src)}" data-index="${i}" aria-label="Открыть материал ${i+1} из ${all.length}"><img src="${esc(thumb)}" alt="${esc(project.title)} — материал ${i+1}" loading="lazy"><span>${String(i+1).padStart(2,'0')}</span></button>`)}
 const archive=`<section class="all-materials" id="all-materials"><div class="all-materials-head"><span>МАТЕРИАЛЫ / ${all.length}</span><h2>РАССМОТРЕТЬ<br>БЛИЖЕ.</h2><p>Крупные кадры проекта можно открыть и листать стрелками. Для работающих цифровых проектов рядом есть ссылка на оригинал.</p></div><div class="gallery-grid">${grouped.join('')}</div></section>`;
 const next=main?PORTFOLIO.featured[(PORTFOLIO.featured.indexOf(project)+1)%PORTFOLIO.featured.length]:null;
 root.innerHTML=`<div class="case-layout">${menu}<div class="case-stage">${opening}${story}${archive}${next?`<a class="next-case" href="case.html?id=${encodeURIComponent(next.id)}"><span>СЛЕДУЮЩИЙ ПРОЕКТ</span><strong>${esc(next.title)} ↗</strong></a>`:''}<div class="case-end-links"><a href="index.html#projects">← ВСЕ ПРОЕКТЫ</a><a href="mailto:berezinapk@yandex.ru">ОБСУДИТЬ ПРОЕКТ ↗</a></div></div></div>`;
 const viewer=document.querySelector('#viewer'),vImg=document.querySelector('#viewer-image'),vCount=document.querySelector('#viewer-count'),vCaption=document.querySelector('#viewer-caption');let currentIndex=0;
 const viewerItems=[...new Set([visual,...(CASE_STORY[id]||[]).flat(),...all.map(item=>item.src)])];
 function show(index){currentIndex=(index+viewerItems.length)%viewerItems.length;vImg.src=viewerItems[currentIndex];vImg.alt=`${project.title} — материал ${currentIndex+1}`;vCount.textContent=`${String(currentIndex+1).padStart(2,'0')} / ${String(viewerItems.length).padStart(2,'0')}`;vCaption.textContent=`${project.title} · материал ${currentIndex+1}`}
 document.querySelectorAll('[data-src]').forEach(button=>button.addEventListener('click',()=>{show(Math.max(0,viewerItems.indexOf(button.dataset.src)));viewer.showModal()}));
 document.querySelector('#viewer-close').onclick=()=>viewer.close();document.querySelector('#viewer-prev').onclick=()=>show(currentIndex-1);document.querySelector('#viewer-next').onclick=()=>show(currentIndex+1);viewer.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')show(currentIndex-1);if(event.key==='ArrowRight')show(currentIndex+1)});viewer.addEventListener('click',event=>{if(event.target===viewer)viewer.close()});
}
