const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const featureArt={vedati:'assets/pdf/covers/vedati.webp',arca:'assets/pdf/covers/arca.webp',luvka:'assets/pdf/covers/luvka.webp',trueshkowski:'assets/pdf/pranna/017.webp',mahajuga:'assets/pdf/covers/mahajuga.webp',techstack:'assets/technopryad-cover.png'};
const floatArt={vedati:'assets/pdf/vedati/036.webp',arca:'assets/pdf/arca/030.webp',luvka:'assets/pdf/luvka/027.webp',trueshkowski:'assets/pdf/pranna/016.webp',mahajuga:'assets/pdf/mahajuga/054.webp',techstack:'assets/live/technopryad/generator-01.webp'};
const archiveArt={seven:'assets/pdf/seven/019.webp',type:'assets/pdf/raw/025.webp',lsp:'assets/live/lsp/readymag-cover.webp',yoshi:'assets/pdf/yoshi/012.webp',pranna:'assets/pdf/pranna/033.webp',eden:'assets/pdf/eden/015.webp',glasses:'assets/pdf/hues/cover.webp',ai:'assets/full/ai/018.webp','eden-ai':'assets/full/eden-ai/016.webp'};
const categories={vedati:'web research',arca:'app research',luvka:'web research',trueshkowski:'brand',mahajuga:'object',techstack:'web'};
const archiveCrops={ai:[16.1,25,23,25],'eden-ai':[16.1,13,72.6,86.8]};
function archiveImage(p){const crop=archiveCrops[p.id],src=archiveArt[p.id]||p.cover;if(p.id==='seven')return `<span class="archive-cover-clip"><img src="${esc(src)}" alt="${esc(p.title)} — материал проекта" loading="lazy"></span>`;if(!crop)return `<img src="${esc(src)}" alt="${esc(p.title)} — материал проекта" loading="lazy">`;const [x,y,w,h]=crop,ratio=(w*2445)/(h*1335);return `<span class="archive-crop" style="aspect-ratio:${ratio};height:auto"><img src="${esc(src)}" alt="${esc(p.title)} — материал проекта" loading="lazy" style="width:${10000/w}%;height:${10000/h}%;left:${-100*x/w}%;top:${-100*y/h}%"></span>`}
document.querySelector('#featured').innerHTML=PORTFOLIO.featured.map((p,i)=>`<a class="project-tile tile-${i+1}" href="case.html?id=${encodeURIComponent(p.id)}" data-category="${categories[p.id]}" style="--tile-color:${esc(p.accent)}"><div class="tile-art"><img src="${esc(featureArt[p.id]||p.cover)}" alt="${esc(p.title)} — материал проекта" loading="${i<2?'eager':'lazy'}"></div><div class="tile-float"><img src="${esc(floatArt[p.id])}" alt="Ещё один визуальный материал проекта ${esc(p.title)}" loading="lazy"></div><div class="tile-label"><span class="tile-num">0${i+1}</span><span><strong>${esc(p.title)}</strong><small>${esc(p.type)}</small></span><b><svg class="icon" aria-hidden="true" focusable="false"><use href="icons.svg#arrow-up-right"></use></svg></b></div></a>`).join('');
document.querySelector('#archive-grid').innerHTML=PORTFOLIO.archive.map((p,i)=>`<a class="more-item item-${esc(p.id)}" href="case.html?id=${encodeURIComponent(p.id)}">${archiveImage(p)}<span>${String(i+7).padStart(2,'0')} / ${esc(p.type)}</span><strong>${esc(p.title)}</strong><b><svg class="icon" aria-hidden="true" focusable="false"><use href="icons.svg#arrow-up-right"></use></svg></b></a>`).join('');
const canvas=document.querySelector('.project-canvas');document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===button));const value=button.dataset.filter;canvas.classList.toggle('filtered',value!=='all');canvas.querySelectorAll('.project-tile').forEach(tile=>tile.hidden=value!=='all'&&!tile.dataset.category.split(' ').includes(value))}));
